services:
  - type: worker
    name: plane-worker
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: |
      cd apps/api
      pip install -r requirements.txt
    startCommand: |
      cd apps/api
      ./bin/docker-entrypoint-worker-render.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: plane.settings.production
